name: pyogame
on:
  pull_request:
  push:
    branches: [ develop ]
jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          ref: develop
      - name: python3.8
        uses: docker://python:3.8
      - name: dependecys
        run: pip install -r requirements.txt
      - name: valid
        run: python -c "from ogame import OGame, test, constants"
      #- name: test
      # run: python3 -c "from ogame import OGame; empire = OGame('U', 'E', 'P'); empire.test()"


